# Check declaration comments only.
scope: declarations

# Optional patterns can exclude comment lines.
# exclude:
  # Exclude experiment directories.
  # - "llama3/experiments/.*"
  # - "experiments/.*"

# Check periods at the end of sentences.
period: true

# Check that first letter of each sentence is capital.
capital: false
