package openapi

// OpenAPI specs are generated by the Makefile's 'openapi' target.
// Run: make openapi
//
// The generation process:
// 1. swag v2 natively generates OpenAPI 3.1 from code annotations
// 2. Generated files are renamed from swagger.* to openapi.*
// 3. Intermediate docs.go is removed (not needed with //go:embed)
// 4. Final openapi.json and openapi.yaml are embedded via embed.go
