package openapi

// OpenAPI specs are generated by the Makefile's 'openapi' target.
// Run: make openapi
//
// The generation process:
// 1. swag generates Swagger 2.0 from code annotations
// 2. swagger2openapi converts to OpenAPI 3.0
// 3. Intermediate files (swagger.json, swagger.yaml, docs.go) are removed
// 4. Final openapi.json and openapi.yaml are embedded via embed.go
